data_cfg:
  dataset_name: CCGR
  dataset_root: /7T/zsndata3/CCGR/
  dataset_partition: ./datasets/CCGR/CCGR.json
  num_workers: 4
  remove_no_gallery: false
  data_in_use: par
  test_dataset_name: CCGR

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 320000
  save_name: GaitGL_PAR
  eval_func: evaluate_CCGR
  sampler:
    batch_size: 2
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 571

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: GaitGL_PAR
  sync_BN: true
  total_iter: 320000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
